'use strict';
const QUESTION_BANK = {
  A: [
    { def: "Empieza con A: Ave rapaz de gran envergadura, símbolo nacional en muchos países", resp: "ÁGUILA" },
    { def: "Empieza con A: Fruto tropical amarillo y alargado llamado piña en España", resp: "ANANÁ" },
    { def: "Empieza con A: Instrumento de cuerda con forma triangular usado en orquestas", resp: "ARPA" },
    { def: "Empieza con A: Gesto afectuoso de rodear a alguien con los brazos", resp: "ABRAZO" },
    { def: "Con la A: Capital de Francia, llamada la ciudad de la luz", resp: "PARIS" },
    { def: "Con la A: Cuarto planeta del sistema solar, el planeta rojo", resp: "MARTE" },
  ],
  B: [
    { def: "Empieza con B: Mamífero marino más grande del planeta", resp: "BALLENA" },
    { def: "Empieza con B: Edificio público donde se guardan y prestan libros", resp: "BIBLIOTECA" },
    { def: "Empieza con B: Recipiente de vidrio o plástico para guardar líquidos", resp: "BOTELLA" },
    { def: "Empieza con B: Danza de pareja de ritmo sincopado originaria de Cuba", resp: "BOLERO" },
    { def: "Con la B: Metal rojizo, muy buen conductor de electricidad", resp: "COBRE" },
    { def: "Con la B: Árbol de madera muy dura, símbolo de fortaleza", resp: "ROBLE" },
  ],
  C: [
    { def: "Empieza con C: Animal camélido del desierto con joroba", resp: "CAMELLO" },
    { def: "Empieza con C: Ave de gran envergadura, emblema de los Andes", resp: "CÓNDOR" },
    { def: "Empieza con C: Segunda ciudad más poblada de Argentina, famosa por sus sierras", resp: "CÓRDOBA" },
    { def: "Empieza con C: Instrumento de viento de madera con boquilla de caña", resp: "CLARINETE" },
    { def: "Con la C: Oscurecimiento de un astro por la interposición de otro cuerpo", resp: "ECLIPSE" },
    { def: "Con la C: Montaña de origen ígneo que puede arrojar lava y ceniza", resp: "VOLCÁN" },
  ],
  D: [
    { def: "Empieza con D: Animal prehistórico de gran tamaño, extinto hace millones de años", resp: "DINOSAURIO" },
    { def: "Empieza con D: Último día de la semana en el calendario cristiano", resp: "DOMINGO" },
    { def: "Empieza con D: Mamífero marino muy inteligente conocido por su sonrisa", resp: "DELFÍN" },
    { def: "Empieza con D: Ser mágico y pequeño del folclore europeo, travieso y astuto", resp: "DUENDE" },
    { def: "Con la D: Capital de España y ciudad más grande del país", resp: "MADRID" },
    { def: "Con la D: Conjunto de todo lo existente: galaxias, planetas y estrellas", resp: "MUNDO" },
  ],
  E: [
    { def: "Empieza con E: Animal terrestre de mayor tamaño, con trompa y colmillos", resp: "ELEFANTE" },
    { def: "Empieza con E: Deporte de combate con espadas donde se busca tocar al adversario", resp: "ESGRIMA" },
    { def: "Empieza con E: País africano famoso por sus pirámides y el río Nilo", resp: "EGIPTO" },
    { def: "Empieza con E: Figura geométrica perfectamente redonda en tres dimensiones", resp: "ESFERA" },
    { def: "Con la E: Segundo planeta del sistema solar, el más brillante del cielo nocturno", resp: "VENUS" },
    { def: "Con la E: Punto cardinal opuesto al este", resp: "OESTE" },
  ],
  F: [
    { def: "Empieza con F: Instrumento de viento de madera que se toca horizontalmente", resp: "FLAUTA" },
    { def: "Empieza con F: Deporte más popular del mundo, se juega con los pies", resp: "FÚTBOL" },
    { def: "Empieza con F: Torre con luz en la costa que guía a los barcos de noche", resp: "FARO" },
    { def: "Empieza con F: Proceso por el que las plantas producen su alimento con luz solar", resp: "FOTOSÍNTESIS" },
    { def: "Con la F: Deporte que se juega en campo verde con palos y hoyos en el piso", resp: "GOLF" },
    { def: "Con la F: Prenda de abrigo que se enrolla alrededor del cuello en invierno", resp: "BUFANDA" },
  ],
  G: [
    { def: "Empieza con G: Instrumento de cuerda punteada, protagonista de la música argentina", resp: "GUITARRA" },
    { def: "Empieza con G: Ave marina blanca que vive en costas y puertos", resp: "GAVIOTA" },
    { def: "Empieza con G: Gran masa de hielo que avanza lentamente por la montaña", resp: "GLACIAR" },
    { def: "Empieza con G: Ciencia que estudia la Tierra, sus países y accidentes naturales", resp: "GEOGRAFÍA" },
    { def: "Con la G: Baile rioplatense de pareja, patrimonio cultural de Argentina y Uruguay", resp: "TANGO" },
    { def: "Con la G: Ser celestial con alas de la tradición religiosa judeo-cristiana", resp: "ÁNGEL" },
  ],
  H: [
    { def: "Empieza con H: Mamífero de gran tamaño con piel gruesa que vive en ríos africanos", resp: "HIPOPÓTAMO" },
    { def: "Empieza con H: Línea imaginaria donde el cielo parece encontrarse con la tierra", resp: "HORIZONTE" },
    { def: "Empieza con H: Fenómeno meteorológico de vientos muy fuertes que giran en espiral", resp: "HURACÁN" },
    { def: "Empieza con H: Persona conocida y admirada por sus actos de valentía extraordinaria", resp: "HÉROE" },
    { def: "Con la H: Ensenada de aguas tranquilas resguardada del oleaje marino", resp: "BAHÍA" },
    { def: "Con la H: Verdura alargada de color naranja, muy rica en vitamina A", resp: "ZANAHORIA" },
  ],
  I: [
    { def: "Empieza con I: Reptil tropical de gran tamaño, parecido a un lagarto", resp: "IGUANA" },
    { def: "Empieza con I: Invento de Gutenberg que permitió reproducir textos en masa", resp: "IMPRENTA" },
    { def: "Empieza con I: Porción de tierra rodeada de agua por todos sus lados", resp: "ISLA" },
    { def: "Empieza con I: País del sur de Asia famoso por el Taj Mahal y el yoga", resp: "INDIA" },
    { def: "Con la I: Estación del año con flores, temperaturas suaves y lluvias", resp: "PRIMAVERA" },
    { def: "Con la I: Instrumento de cuerda frotada, el más agudo de la orquesta sinfónica", resp: "VIOLÍN" },
  ],
  J: [
    { def: "Empieza con J: Gran felino americano de manchas circulares llamadas rosetas", resp: "JAGUAR" },
    { def: "Empieza con J: Animal africano con el cuello más largo del reino animal", resp: "JIRAFA" },
    { def: "Empieza con J: Piedra o adorno precioso que se usa como ornamento", resp: "JOYA" },
    { def: "Empieza con J: Persona que dicta sentencias e imparte justicia en un tribunal", resp: "JUEZ" },
    { def: "Con la J: Viaje largo, especialmente realizado por mar o por aire", resp: "VIAJE" },
    { def: "Con la J: Aparato que mide el tiempo con agujas sobre un cuadrante o pantalla", resp: "RELOJ" },
  ],
  K: [
    { def: "Empieza con K: Marsupial australiano de vida arborícola que come hojas de eucalipto", resp: "KOALA" },
    { def: "Empieza con K: Vestimenta tradicional japonesa de tela de seda con cinturón ancho", resp: "KIMONO" },
    { def: "Empieza con K: Arte marcial japonés de golpes y patadas con cinturones de colores", resp: "KARATE" },
    { def: "Empieza con K: Embarcación ligera y alargada que se impulsa con remos dobles", resp: "KAYAK" },
    { def: "Con la K: Prenda de baño de dos piezas de origen polinésico", resp: "BIKINI" },
    { def: "Con la K: Excursión a pie por montañas con botas y mochila", resp: "TREKKING" },
  ],
  L: [
    { def: "Empieza con L: Líquido blanco y nutritivo que producen los mamíferos para sus crías", resp: "LECHE" },
    { def: "Empieza con L: Satélite natural que orbita la Tierra y brilla en el cielo nocturno", resp: "LUNA" },
    { def: "Empieza con L: Reptil escamoso parecido a una lagartija pero de mayor tamaño", resp: "LAGARTO" },
    { def: "Empieza con L: Idioma de los romanos, base del español y otras lenguas romances", resp: "LATÍN" },
    { def: "Con la L: Diente largo y puntiagudo de elefantes, jabalíes y otras fieras", resp: "COLMILLO" },
    { def: "Con la L: Mamífero marino inteligente con aleta dorsal triangular, muy sociable", resp: "DELFÍN" },
  ],
  M: [
    { def: "Empieza con M: Insecto de alas coloridas que nace de una oruga tras metamorfosis", resp: "MARIPOSA" },
    { def: "Empieza con M: Gran elevación natural del terreno con cima generalmente nevada", resp: "MONTAÑA" },
    { def: "Empieza con M: Sustancia dulce y espesa que producen las abejas en sus colmenas", resp: "MIEL" },
    { def: "Empieza con M: Cereal americano de granos amarillos, base de la dieta latinoamericana", resp: "MAÍZ" },
    { def: "Con la M: Conjunto de notas musicales que sirve de himno oficial de una nación", resp: "HIMNO" },
    { def: "Con la M: Terreno dedicado al cultivo de cereales o plantas agrícolas", resp: "CAMPO" },
  ],
  N: [
    { def: "Empieza con N: Masa de vapor de agua que flota en el cielo y puede producir lluvia", resp: "NUBE" },
    { def: "Empieza con N: Parte del rostro que sirve para respirar y percibir olores", resp: "NARIZ" },
    { def: "Empieza con N: Persona que dirige y lleva a destino una embarcación en el mar", resp: "NAVEGANTE" },
    { def: "Empieza con N: Undécimo mes del año en el calendario gregoriano", resp: "NOVIEMBRE" },
    { def: "Con la N: Cuerpo celeste que orbita alrededor de una estrella, como la Tierra", resp: "PLANETA" },
    { def: "Con la N: Trayectoria continua sin grosor, que puede ser recta o curva", resp: "LÍNEA" },
  ],
  Ñ: [
    { def: "Empieza con Ñ: Ave corredora de gran tamaño nativa de las pampas argentinas", resp: "ÑANDÚ" },
    { def: "Empieza con Ñ: Pasta de harina de papa típica de la cocina italiana y argentina", resp: "ÑOQUI" },
    { def: "Con la Ñ: Persona de corta edad, especialmente varón", resp: "NIÑO" },
    { def: "Con la Ñ: Idioma que se habla en Argentina, España y gran parte de América", resp: "ESPAÑOL" },
    { def: "Con la Ñ: Período de doce meses que tarda la Tierra en orbitar el Sol", resp: "AÑO" },
    { def: "Con la Ñ: Arácnido que teje telas para atrapar insectos y otros animales", resp: "ARAÑA" },
  ],
  O: [
    { def: "Empieza con O: Gran extensión de agua salada que cubre gran parte del planeta", resp: "OCÉANO" },
    { def: "Empieza con O: Conjunto de músicos que interpretan obras clásicas en concierto", resp: "ORQUESTA" },
    { def: "Empieza con O: Estación del año en que las hojas de los árboles cambian de color y caen", resp: "OTOÑO" },
    { def: "Empieza con O: Instrumento de teclado presente en las catedrales e iglesias", resp: "ÓRGANO" },
    { def: "Con la O: Aparato con pantalla que permite llamar y acceder a internet", resp: "TELÉFONO" },
    { def: "Con la O: Bebida espesa de color marrón hecha con leche caliente y cacao", resp: "CHOCOLATE" },
  ],
  P: [
    { def: "Empieza con P: Antigua construcción egipcia de base cuadrada y lados triangulares", resp: "PIRÁMIDE" },
    { def: "Empieza con P: Ave doméstica blanca, símbolo de la paz en todo el mundo", resp: "PALOMA" },
    { def: "Empieza con P: País sudamericano cuya capital es Lima", resp: "PERÚ" },
    { def: "Empieza con P: Persona que viaja en un vehículo sin ser quien lo conduce", resp: "PASAJERO" },
    { def: "Con la P: Representación gráfica de la Tierra o parte de ella sobre papel o pantalla", resp: "MAPA" },
    { def: "Con la P: Engaño o artificio tendido para que alguien caiga en él", resp: "TRAMPA" },
  ],
  Q: [
    { def: "Empieza con Q: Alimento lácteo sólido obtenido por coagulación de la leche", resp: "QUESO" },
    { def: "Empieza con Q: Ciencia que estudia la composición y propiedades de la materia", resp: "QUÍMICA" },
    { def: "Empieza con Q: Personaje literario de Cervantes que luchaba contra molinos de viento", resp: "QUIJOTE" },
    { def: "Empieza con Q: Lesión en la piel causada por exposición excesiva al sol", resp: "QUEMADURA" },
    { def: "Con la Q: Bebida alcohólica mexicana obtenida por destilación del agave azul", resp: "TEQUILA" },
    { def: "Con la Q: Insecto hematófago que puede transmitir el dengue y la malaria", resp: "MOSQUITO" },
  ],
  R: [
    { def: "Empieza con R: Flor fragante con espinas, símbolo del amor romántico", resp: "ROSA" },
    { def: "Empieza con R: Aparato que mide el tiempo con agujas sobre un cuadrante numerado", resp: "RELOJ" },
    { def: "Empieza con R: Gran herbívoro de piel gruesa y uno o dos cuernos en el hocico", resp: "RINOCERONTE" },
    { def: "Empieza con R: Corriente de agua dulce que nace en las montañas y desemboca en el mar", resp: "RÍO" },
    { def: "Con la R: Planta de tronco leñoso con ramas y hojas, más alta que un arbusto", resp: "ÁRBOL" },
    { def: "Con la R: Conjunto de plantas comestibles de hoja verde que se consumen en ensalada", resp: "VERDURA" },
  ],
  S: [
    { def: "Empieza con S: Estrella que da luz y calor a nuestro planeta, el tercero del sistema solar", resp: "SOL" },
    { def: "Empieza con S: Reptil sin patas que se desplaza ondulando su cuerpo sobre el suelo", resp: "SERPIENTE" },
    { def: "Empieza con S: Danza brasileña de ritmo contagioso relacionada con el carnaval de Río", resp: "SAMBA" },
    { def: "Empieza con S: Herramienta de corte con hoja dentada y mango, usada en carpintería", resp: "SIERRA" },
    { def: "Con la S: Palabra que los concursantes dicen en Pasapalabra para saltear una pregunta", resp: "PASAPALABRA" },
    { def: "Con la S: Planta pequeña y esponjosa de color verde que crece en lugares húmedos", resp: "MUSGO" },
  ],
  T: [
    { def: "Empieza con T: Gran felino rayado originario de Asia, el mayor de los félidos", resp: "TIGRE" },
    { def: "Empieza con T: Baile rioplatense de pareja, declarado patrimonio cultural de Argentina", resp: "TANGO" },
    { def: "Empieza con T: Instrumento óptico que amplía la imagen de objetos lejanos como estrellas", resp: "TELESCOPIO" },
    { def: "Empieza con T: Planeta en que vivimos, el tercero del sistema solar por distancia al Sol", resp: "TIERRA" },
    { def: "Con la T: Hierba aromática de hojas pequeñas, muy usada en la cocina mediterránea", resp: "MENTA" },
    { def: "Con la T: Deportista que participa en pruebas de carreras, saltos o lanzamientos", resp: "ATLETA" },
  ],
  U: [
    { def: "Empieza con U: Ser mitológico con forma de caballo blanco y un cuerno en la frente", resp: "UNICORNIO" },
    { def: "Empieza con U: Conjunto de todo lo existente, incluyendo galaxias y materia oscura", resp: "UNIVERSO" },
    { def: "Empieza con U: Instrumento de cuerda de cuatro cuerdas típico de Hawái", resp: "UKELELE" },
    { def: "Empieza con U: Institución educativa de nivel superior donde se dictan carreras de grado", resp: "UNIVERSIDAD" },
    { def: "Con la U: Masa de vapor de agua que flota en el cielo y puede producir lluvia o nieve", resp: "NUBE" },
    { def: "Con la U: Animal marino con ocho tentáculos que expulsa tinta como mecanismo de defensa", resp: "PULPO" },
  ],
  V: [
    { def: "Empieza con V: Instrumento de cuerda frotada, el más agudo de la familia orquestal", resp: "VIOLÍN" },
    { def: "Empieza con V: Montaña de origen ígneo que puede arrojar lava, gases y ceniza", resp: "VOLCÁN" },
    { def: "Empieza con V: Ser de ficción que bebe sangre humana y teme la luz del sol", resp: "VAMPIRO" },
    { def: "Empieza con V: Desplazamiento de masas de aire de zonas de alta a baja presión", resp: "VIENTO" },
    { def: "Con la V: Animal doméstico lanudo que produce lana y emite un sonido característico", resp: "OVEJA" },
    { def: "Con la V: Flor roja o rosada de tallo largo, muy popular en los ramos y jardines", resp: "CLAVEL" },
  ],
  W: [
    { def: "Empieza con W: Tecnología inalámbrica que permite conectarse a internet sin cables", resp: "WIFI" },
    { def: "Empieza con W: Bebida alcohólica de malta o cereales, de origen escocés o irlandés", resp: "WHISKY" },
    { def: "Empieza con W: Deporte acuático en que se navega sobre una tabla impulsada por olas", resp: "WINDSURF" },
    { def: "Empieza con W: Género cinematográfico ambientado en el Lejano Oeste norteamericano", resp: "WESTERN" },
    { def: "Con la W: Fruta tropical pequeña de piel marrón peluda con interior verde y semillas negras", resp: "KIWI" },
    { def: "Con la W: Archipiélago del Pacífico famoso por sus volcanes, estado número 50 de EE.UU.", resp: "HAWÁI" },
  ],
  X: [
    { def: "Empieza con X: Instrumento de percusión formado por láminas de madera de distintos tamaños", resp: "XILÓFONO" },
    { def: "Empieza con X: Técnica de grabado artístico sobre madera o linóleo para hacer impresiones", resp: "XILOGRAFÍA" },
    { def: "Empieza con X: Miedo exagerado e irracional hacia los extranjeros o lo extranjero", resp: "XENOFOBIA" },
    { def: "Empieza con X: Sistema de copia de documentos mediante electricidad estática, sin tinta húmeda", resp: "XEROGRAFÍA" },
    { def: "Con la X: Deporte de combate entre dos contrincantes con puños enguantados sobre un cuadrilátero", resp: "BOXEO" },
    { def: "Con la X: Conjunto de palabras o términos propios de una lengua o de una disciplina", resp: "LÉXICO" },
  ],
  Y: [
    { def: "Empieza con Y: Embarcación de recreo impulsada a vela o a motor, de uso particular", resp: "YATE" },
    { def: "Empieza con Y: Disciplina física y mental de origen hindú que busca el equilibrio interior", resp: "YOGA" },
    { def: "Empieza con Y: Planta tropical de raíz comestible, base de la dieta en muchas regiones", resp: "YUCA" },
    { def: "Empieza con Y: Material blanco y frágil usado en esculturas y para inmovilizar fracturas óseas", resp: "YESO" },
    { def: "Con la Y: Persona que hace reír al público en circos con disfraces y maquillaje exagerado", resp: "PAYASO" },
    { def: "Con la Y: Prenda de punto de lana o algodón que cubre el torso y los brazos", resp: "JERSEY" },
  ],
  Z: [
    { def: "Empieza con Z: Mamífero carnívoro de cola esponjosa, muy astuto en los cuentos populares", resp: "ZORRO" },
    { def: "Empieza con Z: Calzado que cubre y protege el pie y parte del tobillo al caminar", resp: "ZAPATO" },
    { def: "Empieza con Z: Parque o recinto donde se exhiben animales de distintas especies al público", resp: "ZOOLÓGICO" },
    { def: "Empieza con Z: Jugo de frutas o verduras frescas, especialmente de cítricos", resp: "ZUMO" },
    { def: "Con la Z: Espacio público central de una ciudad o pueblo, rodeado de edificios y árboles", resp: "PLAZA" },
    { def: "Con la Z: Tercer mes del año en el calendario gregoriano", resp: "MARZO" },
  ],
};